frase = 'Curso em Video Python'
print(frase.upper().count('E'))
print(len(frase.strip()))
frase.replace('Python', 'Android')
frase = frase.replace('Python', 'Android')
print(frase)
print('Curso' in frase)
print(frase.lower().find('video'))
print(frase.split())
dividido = frase.split()
print(dividido[0])
print(dividido[2][3])